[package]
name = "abc173"
version = "0.1.0"
authors = ["Ryosuke Hayashi <hayashi@hayashikun.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.1"
ndarray = "0.13.1"